import { Manrope } from 'next/font/google';
import '../(site)/globals.css';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

const manrope = Manrope({ subsets: ['cyrillic', 'latin'] });

export default function Authentication({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={manrope.className}>{children}</body>
		</html>
	);
}
